# Generated by Django 3.2.9 on 2021-11-14 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticlepage",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Only for visitor display",
                verbose_name="Publication date",
            ),
        ),
    ]
